name: Publish image do Docker Hub
on:
  [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build . -t petermarynczak/hello-docker-hub:latest
      - name: publish
        run: |
          docker push petermarynczak/hello-docker-hub:latest
